export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_CLEAR_ITEMS = "CART_CLEAR_ITEMS";

export const CATEGORY_LIST = "CATEGORY_LIST";
export const CATEGORY_CHANGE = "CATEGORY_CHANGE";

export const CURRENCY_LIST = "CURRENCY_LIST";
export const CURRENCY_CHANGE = "CURRENCY_CHANGE";

export const CURRENT_PRODUCT_SAVE = "CURRENT_PRODUCT_SAVE";
export const CURRENT_PRODUCT_ATTRIBUTES = "CURRENT_PRODUCT_ATTRIBUTES";
export const CART_CHANGE_QTY = "CART_CHANGE_QTY";


export const START_CATEGORY = "all";
export const START_CURRENCY_SYMBOL = "$";
export const START_CURRENCY_LABEL = "USD";

