export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_CLEAR_ITEMS = "CART_CLEAR_ITEMS";

export const CATEGORY_LIST = "CATEGORY_LIST";
export const CATEGORY_CHANGE = "CATEGORY_CHANGE";

export const CURRENCY_LIST = "CURRENCY_LIST";
export const CURRENCY_CHANGE = "CURRENCY_CHANGE";

export const START_CATEGORY = "all";
export const START_CURRENCY_SYMBOL = "$";
export const START_CURRENCY_LABEL = "USD";

